export enum HttpStatus {
    SUCCESS_OK = 200,
    SUCCESS_CREATED = 201,
    SUCCESS_ACCEPTED_NOT_COMPLETED = 202,
    SUCCESS_NO_CONTENT = 204,

    CLIENT_ERROR_BAD_REQUEST = 400,
    CLIENT_ERROR_UNAUTHORIZED = 401,
    CLIENT_ERROR_PAYMENT_REQUIRED = 402,
    CLIENT_ERROR_FORBIDDEN = 403,
    CLIENT_ERROR_NOT_FOUND = 404,
    CLIENT_ERROR_TIMEOUT = 408,
    CLIENT_ERROR_PAYLOAD_TOO_LARGE = 413,

    SERVER_ERROR_INTERNAL = 500,
    SERVER_ERROR_NOT_IMPLEMENTED = 501,
    SERVER_ERROR_BAD_GATEWAY = 502,
    SERVER_ERROR_SERVICE_UNAVAILABLE = 503,
    SERVER_ERROR_TIMEOUT = 504,
}
